import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import AuthButton from "@/components/AuthButton";
import CustomCursor from "@/components/CustomCursor";
import { auth } from "@/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ADMIN_EMAIL = "tomasismy1@gmail.com";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const session = await auth();
  const isAdmin = session?.user?.email === ADMIN_EMAIL;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* <body className="min-h-full flex flex-col cursor-none sm:cursor-none"> */}
      <body className="min-h-full flex flex-col">
        <Nav authSlot={<AuthButton />} isAdmin={isAdmin} />
        {/* <CustomCursor /> */}
        {children}
      </body>
    </html>
  );
}
