import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import AuthButton from "@/components/AuthButton";
import CustomCursor from "@/components/CustomCursor";
import { auth } from "@/auth";
import NextTopLoader from "nextjs-toploader";
import SmoothScroll from "@/components/SmoothScroll";
import AnimatedBackground from "@/components/background/AnimatedBackground";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Felix Portfolio",
  description: "Generated by Felix Quan",
};

const ADMIN_EMAIL = "tomasismy1@gmail.com";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();
  const isAdmin = session?.user?.email === ADMIN_EMAIL;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* <body className="min-h-full flex flex-col cursor-none sm:cursor-none"> */}
      <body className="min-h-full flex flex-col">
        {/* <CustomCursor /> */}
        <div id="stars-container" className="z-0">
          <div id='stars'></div>
          <div id='stars2'></div>
          <div id='stars3'></div>
        </div>
        <NextTopLoader color="#2563eb" height={3} showSpinner={false} />
        <div className="relative z-10">
          <SmoothScroll />
          <Nav authSlot={<AuthButton />} isAdmin={isAdmin} />
          {children}
          <AnimatedBackground />
          <Footer />
        </div>
      </body>
    </html>
  );
}
